name: CI - Build & Run Tests

on:
  push:
    branches: [ main, Sai ]
  pull_request:
    branches: [ main, Sai ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install PlatformIO Core
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Build native environment
      run: |
        platformio run -e native -v

    - name: Run produced test binary
      run: |
        exe=.pio/build/native/program
        if [ -f "$exe" ]; then
          chmod +x "$exe"
          "$exe"
        else
          echo "Executable not found: $exe"
          exit 2
        fi

    - name: Archive test output
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pio-build
        path: .pio/build/native/
